# Generated by Django 5.1.3 on 2025-01-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('image', models.ImageField(default='photos/default.jpg', upload_to='photos')),
            ],
        ),
    ]
