# Generated by Django 5.1.3 on 2025-01-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=50)),
                ('image1', models.ImageField(default='photos/default.jpg', upload_to='photos/voyage')),
                ('image2', models.ImageField(default='photos/default.jpg', upload_to='photos/voyage')),
                ('image3', models.ImageField(default='photos/default.jpg', upload_to='photos/voyage')),
                ('image4', models.ImageField(default='photos/default.jpg', upload_to='photos/voyage')),
            ],
        ),
    ]
