# Generated by Django 5.1.3 on 2025-01-03 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0002_voyage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='titre',
        ),
        migrations.AddField(
            model_name='voyage',
            name='Activités',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voyage',
            name='Destination',
            field=models.CharField(default='Destination Inconnue', max_length=50),
        ),
        migrations.AddField(
            model_name='voyage',
            name='Transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voyage',
            name='agence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agence.agence'),
        ),
        migrations.AddField(
            model_name='voyage',
            name='billet_avion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voyage',
            name='date_depart',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='date_retour',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='description',
            field=models.TextField(default='Aucune description fournie.'),
        ),
        migrations.AddField(
            model_name='voyage',
            name='nom_hotel',
            field=models.CharField(default='Hôtel Inconnu', max_length=50),
        ),
        migrations.AddField(
            model_name='voyage',
            name='note_hotel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voyage',
            name='package',
            field=models.CharField(default='Standard', max_length=50),
        ),
        migrations.AddField(
            model_name='voyage',
            name='prix_adulte',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voyage',
            name='prix_enfant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voyage',
            name='visa',
            field=models.BooleanField(default=False),
        ),
    ]
