# Generated by Django 5.1.3 on 2025-01-03 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0004_agence_password'),
        ('usr', '0003_usr_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeVoyage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usr.usr')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agence.voyage')),
            ],
        ),
    ]
