# Generated by Django 5.1.1 on 2024-11-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='photos/default.jpg', upload_to='photos/%Y/%m/%d'),
        ),
    ]
